database:
    dsn:
    useSqlite: true
    sqlitePath: db.sqlite
    migrateToSqlite: false
server:
    host: 127.0.0.1:8080
branding:
    name: Untitled Forum
categories:
    - name: Programming
      description: Discuss programming languages, frameworks, and tools
    - name: Off-Topic
      description: Anything not related to the forum
administrators:
    - paging
